/// Flutter icons Mcficons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Mcficons
///      fonts:
///       - asset: fonts/Mcficons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Mcficons {
  Mcficons._();

  static const _kFontFam = 'Mcficons';

  static const IconData crab = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData fast_food = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData lunch = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData milk_tea = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData night_meal = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData restaurent = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData beer = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData breakfast = const IconData(0xe809, fontFamily: _kFontFam);
}
